### ISSUE TITLE
OOM while trying to convert a 70B model to 4.75/4.25 bits on a 4090

### ISSUE THREAD

**Issue by Panchovix** [turboderp/exllamav2#11]
Hi there, amazing work as always.

I was trying to quant airoboros 70B 1.4.1 to EXL2 4.75bit, on a 4090, but got OOM.

```
-- Linear: model.layers.1.mlp.up_proj
 -- 0.05:3b/0.95:2b 32g s4         2.17 bpw    rfn_error: 0.07471
 -- 0.25:3b/0.75:2b 32g s4         2.38 bpw    rfn_error: 0.07147
 -- 0.1:4b/0.4:3b/0.5:2b 32g s4    2.72 bpw    rfn_error: 0.06525
 -- 0.1:4b/0.9:3b 32g s4           3.22 bpw    rfn_error: 0.03174
 -- 1.0:3b 128g s4                 3.03 bpw    rfn_error: 0.03467
 -- 1.0:3b 32g s4                  3.13 bpw    rfn_error: 0.03220
 -- 0.05:4b/0.95:3b 32g s4         3.17 bpw    rfn_error: 0.03195
 -- 0.4:4b/0.6:3b 32g s4           3.53 bpw    rfn_error: 0.02977
 -- 0.6:4b/0.4:3b 64g s4           3.66 bpw    rfn_error: 0.02904
 -- 1.0:4b 128g s4                 4.03 bpw    rfn_error: 0.01724
 -- 1.0:4b 32g s4                  4.13 bpw    rfn_error: 0.01503
 -- 1.0:5b 128g s4                 5.03 bpw    rfn_error: 0.00859
 -- 0.1:6b/0.9:5b 32g s4           5.22 bpw    rfn_error: 0.00761
 -- 0.4:6b/0.6:5b 32g s4           5.53 bpw    rfn_error: 0.00724
 -- 1.0:6b 128g s4                 6.03 bpw    rfn_error: 0.00451
 -- 0.1:8b/0.9:6b 128g s4          6.22 bpw    rfn_error: 0.00445
 -- 1.0:8b 32g s4                  8.13 bpw    rfn_error: 0.00299
 -- Time: 9.78 seconds
 -- Linear: model.layers.1.mlp.down_proj
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllamav2\convert.py", line 168, in <module>
    measure_quant(job, save_job, model)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllamav2\conversion\quantize.py", line 246, in measure_quant
    test_quants(module.down_proj, pre_down, down, qparams_options, results)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllamav2\conversion\quantize.py", line 105, in test_quants
    lq.prepare()
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllamav2\conversion\adaptivegptq.py", line 214, in prepare
    hessian_inv = torch.cholesky_inverse(hessian_inv)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.06 GiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 17.64 GiB is allocated by PyTorch, and 4.18 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Is VRAM usage increased, as bits go higher when converting the model?

Also, I have 2x4090. It is possible to split the conversion between the 2 GPUs?

Thanks in advance!

**Comment by ortegaalfredo** [comment]
Have you tried decreasing the quality? BTW airoboros published the 2.2 version already.

**Comment by Panchovix** [comment]
> Have you tried decreasing the quality? BTW airoboros published the 2.2 version already.

@ortegaalfredo  I will get home in some hours and I will try with lower sizes.

And, yep, but for my usage, 1.4.1 is still the best one for me. 2.2 seems to be interesting on the coding side for me, but I will skip it for now. (Tested it on normal GPTQ with 64g)

**Comment by Panchovix** [comment]
Tried 4.25 bits but got OOM after 1 layer.

```
-- Linear: model.layers.2.mlp.up_proj
 -- 0.05:3b/0.95:2b 32g s4         2.17 bpw    rfn_error: 0.10699
 -- 0.25:3b/0.75:2b 32g s4         2.38 bpw    rfn_error: 0.10248
 -- 0.1:4b/0.4:3b/0.5:2b 32g s4    2.72 bpw    rfn_error: 0.09387
 -- 0.1:4b/0.9:3b 32g s4           3.22 bpw    rfn_error: 0.04660
 -- 1.0:3b 128g s4                 3.03 bpw    rfn_error: 0.05096
 -- 1.0:3b 32g s4                  3.13 bpw    rfn_error: 0.04715
 -- 0.05:4b/0.95:3b 32g s4         3.17 bpw    rfn_error: 0.04688
 -- 0.4:4b/0.6:3b 32g s4           3.53 bpw    rfn_error: 0.04370
 -- 0.6:4b/0.4:3b 64g s4           3.66 bpw    rfn_error: 0.04266
 -- 1.0:4b 128g s4                 4.03 bpw    rfn_error: 0.02548
 -- 1.0:4b 32g s4                  4.13 bpw    rfn_error: 0.02217
 -- 1.0:5b 128g s4                 5.03 bpw    rfn_error: 0.01270
 -- 0.1:6b/0.9:5b 32g s4           5.22 bpw    rfn_error: 0.01128
 -- 0.4:6b/0.6:5b 32g s4           5.53 bpw    rfn_error: 0.01074
 -- 1.0:6b 128g s4                 6.03 bpw    rfn_error: 0.00673
 -- 0.1:8b/0.9:6b 128g s4          6.22 bpw    rfn_error: 0.00665
 -- 1.0:8b 32g s4                  8.13 bpw    rfn_error: 0.00462
 -- Time: 9.17 seconds
 -- Linear: model.layers.2.mlp.down_proj
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllamav2\convert.py", line 168, in <module>
    measure_quant(job, save_job, model)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllamav2\conversion\quantize.py", line 246, in measure_quant
    test_quants(module.down_proj, pre_down, down, qparams_options, results)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllamav2\conversion\quantize.py", line 105, in test_quants
    lq.prepare()
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllamav2\conversion\adaptivegptq.py", line 214, in prepare
    hessian_inv = torch.cholesky_inverse(hessian_inv)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.06 GiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 17.64 GiB is allocated by PyTorch, and 4.59 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Panchovix** [comment]
Closing as I got this answer from turbo

```
Yes, it seems like it needs just a little bit more than 24 GB when you exceed 4.0 bits. Problem is that it has to run inference at full precision to use the calibration data, so it needs at least one full-precision layer loaded, along with at least a slice of the hidden state for the 200k tokens it's calibrating on. I'll be working on optimizing that, I guess.
```
