### ISSUE TITLE
Exl2 model fails to run -- RuntimeError: Insufficient size of temp_dq buffer

### ISSUE THREAD

**Issue by truenorth8** [turboderp/exllamav2#138]
Hi. I quantized a model using convert.py as follows:

> python convert.py --bits 2.55 --shard_size 8192 --in_dir /workspace/airoboros-l2-70b-3.1.2 --out_dir /workspace/airoboros-l2-70b-3.1.2_exl_2.55bpw_raw --compile_full /workspace/airoboros-l2-70b-3.1.2_exl_2.55bpw --cal_dataset ../wikitext-1.3-raw.parquet

I then uploaded the compile_full folder to huggingface. However, the quantized model gives me the following error when loading in text-generation-webUI:

```
Traceback (most recent call last):
File "/workspace/text-generation-webui/modules/ui_model_menu.py", line 206, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File "/workspace/text-generation-webui/modules/models.py", line 84, in load_model
output = load_func_map[loader](model_name)
File "/workspace/text-generation-webui/modules/models.py", line 356, in ExLlamav2_HF_loader
return Exllamav2HF.from_pretrained(model_name)
File "/workspace/text-generation-webui/modules/exllamav2_hf.py", line 156, in from_pretrained
return Exllamav2HF(config)
File "/workspace/text-generation-webui/modules/exllamav2_hf.py", line 39, in init
self.ex_model.load(split)
File "/usr/local/lib/python3.10/dist-packages/exllamav2/model.py", line 240, in load
for module in self.modules: module.load()
File "/usr/local/lib/python3.10/dist-packages/exllamav2/attn.py", line 79, in load
self.q_proj.load()
File "/usr/local/lib/python3.10/dist-packages/exllamav2/linear.py", line 51, in load
self.q_handle = ext.make_q_matrix(w, self.temp_dq)
File "/usr/local/lib/python3.10/dist-packages/exllamav2/ext.py", line 155, in make_q_matrix
return ext_c.make_q_matrix(w["q_weight"],

RuntimeError: Insufficient size of temp_dq buffer
```

![image](https://github.com/turboderp/exllamav2/assets/123232491/63f432fa-1063-4069-a2a8-151bd7316255)

Any help would be much appreciated

**Comment by turboderp** [comment]
I would suspect some issue with the vocabulary, but I'd have to give the model a look. Do you have a link to what you uploaded on HF?

**Comment by truenorth8** [comment]
Apologies, I mixed up a config file from another model. All good, thanks
