### ISSUE TITLE
rocm5.2.0 torch run test_inference.py error undefined symbol: hipblasHgemm

### ISSUE THREAD

**Issue by Rane2021** [turboderp/exllamav2#144]
(llama) root@:/data2/02_exllamav2/exllamav2# python test_inference.py -m /data2/models/exllamav2_models/turboderp_Llama2-7B-exl2-4.0bpw -p "Once upon a time,"
Traceback (most recent call last):
  File "test_inference.py", line 2, in <module>
    from exllamav2 import(
  File "/data2/02_exllamav2/exllamav2/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/data2/02_exllamav2/exllamav2/exllamav2/model.py", line 17, in <module>
    from exllamav2.cache import ExLlamaV2CacheBase
  File "/data2/02_exllamav2/exllamav2/exllamav2/cache.py", line 2, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "/data2/02_exllamav2/exllamav2/exllamav2/ext.py", line 14, in <module>
    import exllamav2_ext
ImportError: /root/miniconda3/envs/llama-fac/lib/python3.8/site-packages/exllamav2-0.0.7-py3.8-linux-x86_64.egg/exllamav2_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: hipblasHgemm

**Comment by Rane2021** [comment]
run "python setup.py install" no problem; but error in "test_inference.py"

**Comment by ardfork** [comment]
This project currently only support ROCm 5.6 and above.
