### ISSUE TITLE
Support for Huggingface Fast Tokenizers

### ISSUE THREAD

**Issue by bibekyess** [turboderp/exllamav2#188]
Hello ! I found some Llama2 models using the `FastTokenizer` provided by the Hugging Face tokenizers library, not the `SentencePiece` package used by regular Llama models. For instance, `beomi/llama-2-ko-7b`. 
It seems the current `ExLlamaV2Tokenizer` only support SentencePiece tokenizer, which requires `tokenizer.model`, can you please add support for Hugging Face tokenizers as well? 
I tried changing the file `tokenizer.py` to accomplish it and it worked well in exllama but in exllamav2, it works well sometimes but sometimes it gives following errors.
```bash
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/tabbyAPI/main.py", line 188, in generate_completion
    response_text = model_container.generate(data.prompt, **data.to_gen_params())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/tabbyAPI/model.py", line 230, in generate
    reponse = "".join(gen)
              ^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/tabbyAPI/model.py", line 363, in generate_gen
    chunk, eos, tokens = self.generator.stream()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/exllamav2/exllamav2/generator/streaming.py", line 155, in stream
    next_token, new_text = self._catch_utf8(next_token, new_text)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/exllamav2/exllamav2/generator/streaming.py", line 218, in _catch_utf8
    id_to_ord = self.tokenizer.get_id_to_ord_list()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/exllamav2/exllamav2/tokenizer.py", line 275, in get_id_to_ord_list
    match = self.ord_exp.match(p)
            ^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'
Response: 247 tokens generated in 7.81 seconds (31.63 T/s, context 9 tokens)
INFO:     127.0.0.1:47692 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:34096 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/anaconda3/envs/exllamav2-env/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/tabbyAPI/main.py", line 188, in generate_completion
    response_text = model_container.generate(data.prompt, **data.to_gen_params())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/tabbyAPI/model.py", line 230, in generate
    reponse = "".join(gen)
              ^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/tabbyAPI/model.py", line 363, in generate_gen
    chunk, eos, tokens = self.generator.stream()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/exllamav2/exllamav2/generator/streaming.py", line 155, in stream
    next_token, new_text = self._catch_utf8(next_token, new_text)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bibekyess/exllama_v2_sandbox/exllamav2/exllamav2/generator/streaming.py", line 220, in _catch_utf8
    b = id_to_ord[t]
        ~~~~~~~~~^^^
IndexError: list index out of range
```

It is interesting that sometimes, the inference is successful, while sometimes it is not. So, I want to request for official support of the Huggingface Fast Tokenizers.

Thank you! :)

**Comment by bibekyess** [comment]
Maybe the issue arises because of [TabbyAPI](https://github.com/theroyallab/tabbyAPI/). I created my own FastAPI server and I am not facing such issues.

**Comment by turboderp** [comment]
I've been working on this for most of the day. I have HF tokenizers working more or less, there's just a few kinks to iron out because the EXL2 tokenizer does more than just wrap around SentencePiece. Also apparently bugs in the HF Tokenizer implementation that I have to work around. But getting there.

**Comment by bibekyess** [comment]
Great to hear that! Thank you! :)

**Comment by turboderp** [comment]
It *should* be working now. I've mainly focused on deepseek, and HF tokenization is a deep, deep rabbit hole, so I'll probably need to test a lot more models to fix various edge cases.

**Comment by turboderp** [comment]
It could be. How are you using the model?

**Comment by alexconstant9108** [comment]
Just running `examples/chat.py` as described in the main page

**Comment by turboderp** [comment]
I know the system prompt is inconsistent across the deepseek models. You could try with [ExUI](https://github.com/turboderp/exui) which I've confirmed works well, at least with [my own conversions of 67B-chat](https://huggingface.co/turboderp/deepseek-llm-67B-chat-exl2) and the built-in deepseek prompt format.

**Comment by alexconstant9108** [comment]
Nice! I didn't know you also release quants :) Any plans for 67B-chat 6.0bpw?

**Comment by alexconstant9108** [comment]
> ExUI is more advanced with sessions, model loading/unloading, notepad mode etc.

Unfortunately I am running the models on a cloud machine with no Internet access which I can only access via SSH. Even if I run a web server I can't access it, that's why I am using the command line scripts test_inference.py and chat.py

> ... `-rs 4` it should work. It also seems to be a bit sensitive to repetition penalty, so I would lower it from the default (1.15) to something like `-repp 1.05`.

Thanks for the suggestion! This really fixed the issue. :) Unfortunately now there is another problem. If you give it some programming task where it needs to generate two long functions the starts glitching after 50 lines of code or so:

```User: You are an intelligent programming assistant.\n### Instruction:\nWrite a very well commented function in modern C++ to generate the first 1307 Fibonacci numbers and return the median and average of the list. Do not use recursion.\n### Response:```

```Here is a simple C++ program that generates the first 1307 Fibonacci numbers, calculates the median and average of the list, and prints them out. The program uses a vector to store the Fibonacci numbers for easy access and manipulation.



   #include <iostream>
   #include <vector>
   #include <algorithm>
...

double average = (double) sum / v.size();
     return sum / (double)( 2 ) r  o f  f  f  r  o f  t  h  e  2  o  t  e  n  1  n  o  t  f  o  r  t  h  e  2  o  t  f  o  r  t  h  e  2  o  t  o  r  g  e  t  h  e  2  o  t  h  e  c  o  n  t  e  n  t  e  r  o  f  t  h  e  f  o  r  t  h  e  r  o  m  t  o  s  o  t  h  e  f  o```

Is this a RoPE issue? It shouldn't be the Tokenizer because it only happens after some context and never at the beginning

**Comment by turboderp** [comment]
Well, like I said it's a simple thing, so I just added it, cause why not. Run the chatbot with `--amnesia` and it will forget the context after each response.

**Comment by alexconstant9108** [comment]
> Well, like I said it's a simple thing, so I just added it, cause why not. Run the chatbot with `--amnesia` and it will forget the context after each response.

Are you sure you have pushed to `master`? ;)
BTW I forgot to mention earlier but your project is just amazing. It is unbelievable how fast model inference runs on consumer gpus! Kudos!

**Comment by turboderp** [comment]
Yes, there are *two* buttons I need to click. Ahem.. try it again. (:

**Comment by alexconstant9108** [comment]
The `amesia` feature works perfectly! Thank you! :)

So the following issue only seems to happen with `LoneStriker/deepseek-coder-33b-instruct-6.0bpw-h6-exl2`
>  If you give it some programming task where it needs to generate two long functions the output starts glitching after 50 lines of code or so:

or at least I haven't been able to reproduce it with your Mistral-instruct conversion or with `LoneStriker/deepseek-llm-67b-chat-6.0bpw-h6-exl2`. Although `deepseek-llm-67b-chat` seems kinda meh with its responses. I was kinda expecting much much more given the hype when it got announced a few days ago. Have you had any interesting interactions with it?

**Comment by turboderp** [comment]
>If you give it some programming task where it needs to generate two long functions the output starts glitching after 50 lines of code or so:

This could be related to the RoPE scaling. If the model was converted without that setting, the calibration is going to be very off.

**Comment by alexconstant9108** [comment]
Makes sense. I guess I should convert the Deepseek coder model myself. In that case would a calibration set containing source code be more useful than wikitext-test?

A bit off topic: does the exui come with good presets for the more popular models for values such as minP, maxP, mirostat and so on? If yes then I could "steal" the values from the project :)

**Comment by turboderp** [comment]
From what experiments I and others have done, the calibration dataset doesn't ultimately matter *that* much. But it's probably a good idea to have some code in there, if nothing else then to make sure all the "coding tokens" and their embeddings are accounted for.

As for presets, no. I don't really believe in samplers as a way to fix bad predictions from language models. So the default is just top-K+top-P, with a slight repetition penalty (which is probably a bit too high by default), and everything else is just there because people have requested it. Locally typical sampling has some good theory behind it, I guess?

**Comment by alexconstant9108** [comment]
> From what experiments I and others have done, the calibration dataset doesn't ultimately matter _that_ much. But it's probably a good idea to have some code in there, if nothing else then to make sure all the "coding tokens" and their embeddings are accounted for.

I see. I will have to learn more about python and those parquet files to see how to do that. 
But one thing is certain. There is something WRONG in LoneStriker's conversions of the two deepseek models coder33B and chat67b. I tried the deepseek-llm-67b-chat.Q6_K.gguf version just to compare and it's a totally different universe, while LoneStriker/deepseek-llm-67b-chat-6.0bpw-h6-exl2 feels like a dumb 2-3B model...


> As for presets, no. I don't really believe in samplers as a way to fix bad predictions from language models. So the default is just top-K+top-P, with a slight repetition penalty (which is probably a bit too high by default), and everything else is just there because people have requested it. Locally typical sampling has some good theory behind it, I guess?

To me it all looks like black magic. I just play around with the values until the output starts to look at something that makes sense. If you mean "typical threshold" I still haven't played with it but will soon :)

**Comment by alexconstant9108** [comment]
@turboderp  so I did my own conversion of `deepseek-coder-33b-instruct` following the steps here: https://github.com/turboderp/exllamav2/blob/master/doc/convert.md and the result is exactly the same as with LoneStriker's conversion. The model only works with `rope-scale` 4.0, not with 1.0. Is 4.0 the default value now? And after around 50 lines of generated code starts glitching e.g. repeating one token until exhaustion. Are there any other parameters to tweak, e.g. rope_alpha?

**Comment by turboderp** [comment]
Cleaning up some issues, and this is technically completed.
