### ISSUE TITLE
convert_safetensors doesn't force existing GPU

### ISSUE THREAD

**Issue by Chainfire** [turboderp/exllamav2#34]
On some files (particularly spicyboros-c34-2.2 files 4 through 7) pytorch wants to load the tensors to a GPU I don't have.

```
Traceback (most recent call last):
  File "/home/jorrit/llama/exllamav2/util/convert_safetensors.py", line 19, in <module>
    state_dict = torch.load(file)
  File "/home/jorrit/llama-env-10/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/jorrit/llama-env-10/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/jorrit/llama-env-10/lib/python3.10/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/jorrit/llama-env-10/lib/python3.10/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/jorrit/llama-env-10/lib/python3.10/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "/home/jorrit/llama-env-10/lib/python3.10/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/jorrit/llama-env-10/lib/python3.10/site-packages/torch/serialization.py", line 173, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.
```

epicfilemcnulty's version still works though - https://gist.github.com/epicfilemcnulty/1f55fd96b08f8d4d6693293e37b4c55e

**Comment by turboderp** [comment]
Thanks for the heads up. I've added the `map_location` argument which should address this particular issue. Not sure what other issues there might be, though. Pickle files are a very rich format and can really throw any sort of curveball at you, even malicious code, apparently.
