### ISSUE TITLE
Low context bugs and errors.

### ISSUE THREAD

**Issue by ThomasBaruzier** [turboderp/exllamav2#382]
Hello again.

I was trying to run Qwen 72B on my rtx 3090 at 2.4bpw (LoneStriker quant). To do so, I had to lower the context length to 200 tokens. 

The issue is that exllama either crashes or get stuck when the context window goes below 315 tokens (heavily varies depending on models, does not replicate that behavior all the time).

Here is an example of it getting stuck for 5+ min.
```
screen -mS inference python examples/chat.py -m  ~/storage/gpu-models/LoneStriker_Qwen1.5-72B-Chat-2.4bpw-h6-exl2/ -mode chatml --length 200 --cache_8bit -amnesia 
 -- Model: /home/tyra/storage/gpu-models/LoneStriker_Qwen1.5-72B-Chat-2.4bpw-h6-exl2/                                                                           
 -- Options: ['length: 200']                                                    
 -- Loading model...                                                            
 -- Loading tokenizer...                                                        
 -- Prompt format: chatml                                                       
 -- System prompt:                                                              
                                                                                
You are Chatbort, a large language model. Answer as concisely as possible.      
                                                                                
User: hi                                                                        
                                                                                
^CTraceback (most recent call last):                                            
  File "/home/tyra/files/ai/exllama/examples/chat.py", line 268, in <module>    
    active_context = get_tokenized_context(model.config.max_seq_len - min_space_in_context)                                                                     
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                     
  File "/home/tyra/files/ai/exllama/examples/chat.py", line 179, in get_tokenized_context                                                                       
    for turn in range(len(user_prompts)):                                       
                ^^^^^^^^^^^^^^^^^^^^^^^^                                        
KeyboardInterrupt                 
```

And here is a crash example:
```
screen -mS inference python examples/chat.py -m  ~/storage/gpu-models/silicon-maid-7b-8.0bpw-h8-exl2/ -mode chatml --length 314 --cache_8bit -amnesia
 -- Model: /home/tyra/storage/gpu-models/silicon-maid-7b-8.0bpw-h8-exl2/        
 -- Options: ['length: 314']                                                    
 -- Loading model...                                                            
 -- Loading tokenizer...                                                        
 -- Prompt format: chatml                                                       
 -- System prompt:                                                              
                                                                                
You are Chatbort, a large language model. Answer as concisely as possible.      
                                                                                
User: hi                                                                        
                                                                                
Traceback (most recent call last):                                              
  File "/home/tyra/files/ai/exllama/examples/chat.py", line 289, in <module>    
    res = generator.stream_ex()                                                 
          ^^^^^^^^^^^^^^^^^^^^^                                                 
  File "/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/generator/streaming.py", line 184, in stream_ex                                 
    chunk, eos, chunk_token_ids, probs, ptokens, pprobs, logits = self._stream()
                                                                  ^^^^^^^^^^^^^^
  File "/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/generator/streaming.py", line 267, in _stream                                   
    next_token, next_ptokens, next_pprobs, next_prob, eos, next_logits = self._gen_single_token(self.settings)                                                  
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                  
  File "/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/generator/streaming.py", line 522, in _gen_single_token                         
    position_offsets = self.position_offsets).float().cpu()                     
                                              ^^^^^                             
AttributeError: 'NoneType' object has no attribute 'float' 
```

And another one:
```
screen -mS inference python examples/chat.py -m  ~/storage/gpu-models/NousResearch_Nous-Hermes-2-SOLAR-10.7B/ -mode chatml --length 300 --cache_8bit -amnesia
 -- Model: /home/tyra/storage/gpu-models/NousResearch_Nous-Hermes-2-SOLAR-10.7B/
 -- Options: ['length: 300']                                                    
 -- Loading model...                                                            
 -- Loading tokenizer...                                                        
Traceback (most recent call last):                                              
  File "/home/tyra/files/ai/exllama/examples/chat.py", line 93, in <module>     
    model, tokenizer = model_init.init(args, allow_auto_split = True, max_output_len = 16)                                                                      
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                      
  File "/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/model_init.py", line 124, in init                                               
    tokenizer = ExLlamaV2Tokenizer(config)                                      
                ^^^^^^^^^^^^^^^^^^^^^^^^^^                                      
  File "/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/tokenizer.py", line 119, in __init__                                            
    self.eos_token = (self.tokenizer.eos_token() or self.extended_id_to_piece.get(self.eos_token_id, None)) or self.tokenizer.id_to_piece(self.eos_token_id)    
                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/tokenizers/spm.py", line 39, in id_to_piece                                     
    return self.spm.id_to_piece(idx)                                            
           ^^^^^^^^^^^^^^^^^^^^^^^^^                                            
  File "/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/sentencepiece/__init__.py", line 1179, in _batched_func                                   
    return _func(self, arg)                                                     
           ^^^^^^^^^^^^^^^^                                                     
  File "/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/sentencepiece/__init__.py", line 1172, in _func                                           
    raise IndexError('piece id is out of range.')                               
IndexError: piece id is out of range.   
```

Edit: the crash above is not related to context length, but maybe fp16 loader? I guess it's useful to leave it there.

**Comment by ThomasBaruzier** [comment]
I guess this is also the reason why TabbyAPI crashes at low context length:
```
INFO:     Loading model: 
/home/tyra/storage/gpu-models/LoneStriker_Qwen1.5-72B-Chat-2.4bpw-h6-exl2
INFO:     Loading with a manual GPU split (or a one GPU setup)
Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 163/163 0:00:00
INFO:     Model successfully loaded.
INFO:     Developer documentation: http://127.0.0.1:5000/redoc
INFO:     Completions: http://127.0.0.1:5000/v1/completions
INFO:     Chat completions: http://127.0.0.1:5000/v1/chat/completions
INFO:     Started server process [2671]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:     127.0.0.1:35476 - "GET /v1/models HTTP/1.1" 200
INFO:     127.0.0.1:50720 - "POST 
/v1/chat/completions?path=v1&path=chat&path=completions HTTP/1.1" 200
INFO:     Generation options: {'max_tokens': 89, 'stream': True, 'temperature': 
1.0, 'temperature_last': False, 'smoothing_factor': 0.0, 'top_k': 0, 'top_p': 
1.0, 'top_a': 0.0, 'min_p': 0.0, 'tfs': 1.0, 'typical': 1.0, 'mirostat': False, 
'max_temp': 1.0, 'min_temp': 1.0, 'temp_exponent': 1.0, 'mirostat_tau': 1.5, 
'mirostat_eta': 0.3, 'token_repetition_penalty': 1.0, 'token_frequency_penalty':
0.0, 'token_presence_penalty': 0.0, 'token_repetition_range': -1, 
'token_repetition_decay': 0, 'filters': [], 'token_healing': False, 
'auto_scale_penalty_range': False, 'generate_window': 512, 'add_bos_token': 
True, 'ban_eos_token': False, 'speculative_ngram': False, 'logprobs': 0, 
'stop_conditions': [151643], 'logit_bias': None}

INFO:     Prompt: 
INFO:     <|im_start|>user
INFO:     hello?
INFO:     <|im_end|>
INFO:     <|im_start|>assistant
INFO:     
ERROR:    Traceback (most recent call last):
ERROR:      File 
"/home/tyra/files/ai/tabby/endpoints/OAI/utils/chat_completion.py", line 170, in
stream_generate_chat_completion
ERROR:        async for generation in new_generation:
ERROR:      File "/home/tyra/files/ai/tabby/backends/exllamav2/model.py", line 
644, in generate_gen
ERROR:        async for value in iterate_in_threadpool(sync_generator):
ERROR:      File "/home/tyra/files/ai/tabby/common/concurrency.py", line 34, in 
iterate_in_threadpool
ERROR:        yield await asyncio.to_thread(gen_next, generator)
ERROR:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/usr/lib/python3.11/asyncio/threads.py", line 25, in to_thread
ERROR:        return await loop.run_in_executor(None, func_call)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in
run
ERROR:        result = self.fn(*self.args, **self.kwargs)
ERROR:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/tyra/files/ai/tabby/common/concurrency.py", line 24, in 
gen_next
ERROR:        return next(generator)
ERROR:               ^^^^^^^^^^^^^^^
ERROR:      File "/home/tyra/files/ai/tabby/backends/exllamav2/model.py", line 
935, in generate_gen_sync
ERROR:        raw_generation = self.generator.stream_ex()
ERROR:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File 
"/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/generat
or/streaming.py", line 184, in stream_ex
ERROR:        chunk, eos, chunk_token_ids, probs, ptokens, pprobs, logits = 
self._stream()
ERROR:                                                                      
^^^^^^^^^^^^^^
ERROR:      File 
"/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/generat
or/streaming.py", line 267, in _stream
ERROR:        next_token, next_ptokens, next_pprobs, next_prob, eos, next_logits
= self._gen_single_token(self.settings)
ERROR:                                                                          
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File 
"/home/tyra/files/ai/envs/exllama/lib/python3.11/site-packages/exllamav2/generat
or/streaming.py", line 522, in _gen_single_token
ERROR:        position_offsets = self.position_offsets).float().cpu()
ERROR:                                                  ^^^^^
ERROR:    AttributeError: 'NoneType' object has no attribute 'float'
ERROR:    Sent to request: Chat completion aborted. Please check the server 
console.
^CWARNING:  Shutdown signal called. Exiting gracefully.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2671]
WARNING:  Shutdown signal called. Exiting gracefully.
```

**Comment by turboderp** [comment]
The example chatbot has a somewhat simplistic context management system. By default it reserves 250 tokens for the reply and doesn't have a robust mechanism for handling a total context length that isn't somewhat longer than that. You can limit it by running it with e.g. `--response_chunk 50` which reserves less space of the overall context at a time, leaving room for more prompt. There will be a speed tradeoff and the model will be somewhat unpredictable when used like this.

Not sure about the situation when running Tabby with an extremely small context, but yeah it's probably related.

**Comment by ThomasBaruzier** [comment]
Alright, thanks! 

I guess i'll have to quantize more 🫠
The context here was to evaluate Qwen72B as llama.cpp simply crashes my whole computer (i guess a b450 with a ryzen 3950x is bad)
Anyway 200 tokens was just right for Lonestrickers' lowest quant of Qwen72B for me to somewhat test. It's more of an extreme case rather than anything useful.

Thanks for the reply, have a great day!

**Comment by turboderp** [comment]
If you want to squeeze a little extra VRAM out of it, probably enough for a couple hundred more tokens at least, you can also use the `--cache_q4` and `--low_mem` options. FWIW. Also if you haven't already, make sure Flash-Attention is installed.
