### ISSUE TITLE
KeyError: 'measurement'

### ISSUE THREAD

**Issue by Katehuuh** [turboderp/exllamav2#389]
using `measurement.json`, `python convert.py -i C:\Model-7B -o C:\temp-8.0bpw-h8-exl2 -cf C:\Model-7B-8.0bpw-h8-exl2 --bits 8.0 -hb 8 --length 4096 --measurement_length 4096 --cal_dataset C:\pippa.parquet -m C:\measurement.json`:

```cmd
 !! Warning: calibration rows > 2048 tokens may result in excessive VRAM use
 -- Beginning new job
Traceback (most recent call last):
  File "C:\exllamav2\convert.py", line 119, in <module>
    job["measurement"] = imp_measurement["measurement"]
KeyError: 'measurement'
 !! Warning: calibration rows > 2048 tokens may result in excessive VRAM use
 -- Beginning new job
Traceback (most recent call last):
  File "D:\exllamav2\convert.py", line 119, in <module>
    job["measurement"] = imp_measurement["measurement"]
KeyError: 'measurement'
 !! Warning: calibration rows > 2048 tokens may result in excessive VRAM use
 -- Beginning new job
Traceback (most recent call last):
  File "C:\exllamav2\convert.py", line 119, in <module>
    job["measurement"] = imp_measurement["measurement"]
KeyError: 'measurement'
```

- Win, 554eb7c

**Comment by Katehuuh** [comment]
> Can you share that measurement.json file? It seems to be corrupt somehow.

Empty.. Sorry i miss doc arg `-om`.
