### ISSUE TITLE
ninja compilation error - gcc11

### ISSUE THREAD

**Issue by vasqu** [turboderp/exllamav2#41]
When I've followed the instructions given in the README:
```
git clone https://github.com/turboderp/exllamav2
cd exllamav2
pip install -r requirements.txt

python test_inference.py -m <path_to_model> -p "Once upon a time,"
```
I have encountered build issues with Ninja:
```
Traceback (most recent call last):
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/exllamav2/test_inference.py", line 2, in <module>
    from exllamav2 import(
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/exllamav2/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/exllamav2/exllamav2/model.py", line 12, in <module>
    from exllamav2.linear import ExLlamaV2Linear
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/exllamav2/exllamav2/linear.py", line 5, in <module>
    from exllamav2 import ext
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/exllamav2/exllamav2/ext.py", line 118, in <module>
    exllamav2_ext = load \
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/av11/Documents/coding/gpt-git/gpt-synthetic-data-generation/src/gpt-api/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'exllamav2_ext': [1/12] ...
```
This is only a partial error message since it goes on for a while. Following the ..., it repeats for 12 different parts. 

A partial error later on:
```
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
```
for which I've found this issue: https://github.com/NVlabs/instant-ngp/issues/119 and more specifically the comment https://github.com/NVlabs/instant-ngp/issues/119#issuecomment-1034701258. In my case, installing gcc10 and overwriting the corresponding environment variables was enough to get it running. I know this issue cannot be directly solved here, but it might be worth adding this information somewhere (i.e., gcc10 might be necessary for ninja to work correctly).

**Comment by Tuxinet** [comment]
For me at least, I resolved this issue by installing the latest nvidia and cuda drivers with the .run-files provided by nvidia. Not installing with my distro-packages (Ubuntu)

**Comment by ChrisCates** [comment]
Getting the same error even with GCC 10 and G++ 10 installed.

Ran and restarted with:

```bash
sudo apt install gcc-10 g++-10 -y

sudo update-alternatives --remove-all gcc
sudo update-alternatives --remove-all g++

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 30
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 30

sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
sudo update-alternatives --set cc /usr/bin/gcc

sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
sudo update-alternatives --set c++ /usr/bin/g++

sudo update-alternatives --config gcc
sudo update-alternatives --config g++
```

Running Nvidia Driver `515.105.01`
Running NVCC `V11.7.64`

**Comment by ChrisCates** [comment]
Just tried with `535.104.05` and still no go. Will attempt with V12 `NVCC` now.

**Comment by ChrisCates** [comment]
Finally got it working. It was because I didn't have header files installed for Python.
Check the stack trace for your error. If it's not GCC/G++ related and asks for a `Python.h` header file.

Should contain this in the stack trace:

```bash
/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
   12 | #include <Python.h>
```

Run `python --version` and then install the respective Python header files:

```bash
sudo apt-get install python3.10-dev
```

Hope this helps.

**Comment by turboderp** [comment]
Closing some old issues. Let me know if any of this shows up again.
