### ISSUE TITLE
Error because of string in PyPI flash-attn 2.2.3.post2 version

### ISSUE THREAD

**Issue by TehNomad** [turboderp/exllamav2#45]
I was trying to use Exllamav2 with flash-attn in Text-Generation-UI and I got the following error because the flash-attn 2.2.3.post2 version on PyPI has a string in it. 

```
Traceback (most recent call last):
  File "/home/user/github/text-generation-webui/modules/ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/home/user/github/text-generation-webui/modules/models.py", line 77, in load_model
    output = load_func_map[loader](model_name)
  File "/home/user/github/text-generation-webui/modules/models.py", line 32
7, in ExLlamav2_HF_loader
    from modules.exllamav2_hf import Exllamav2HF
  File "/home/user/github/text-generation-webui/modules/exllamav2_hf.py", line 6, in <module>
    from exllamav2 import ExLlamaV2, ExLlamaV2Cache, ExLlamaV2Config
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/model.py", line 15, in <module>
    from exllamav2.attn import ExLlamaV2Attention
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/attn.py", line 19, in <module>
    flash_attn_ver = [int(t) for t in flash_attn.__version__.split(".")]
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/exllamav2/attn.py", line 19, in <listcomp>
    flash_attn_ver = [int(t) for t in flash_attn.__version__.split(".")]
ValueError: invalid literal for int() with base 10: 'post2'
```
I resolved the error by adding `if t.isdigit()` to the end of line 19 in attn.py

**Comment by turboderp** [comment]
Thanks. I've made the change. I wonder if there's a better way to do this. I'm trying to avoid adding another dependency like `packaging`.
