### ISSUE TITLE
Problem running dynamic Gen.py in examples

### ISSUE THREAD

**Issue by rjmehta1993** [turboderp/exllamav2#518]
I am using Linux and the blessed - Terminal is throwing an error.

Installed blessed using 
`pip install blessed`
```
from blessed import Terminal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/exl19/lib/python3.10/site-packages/blessed/__init__.py", line 14, in <module>
    from blessed.terminal import Terminal  # type: ignore
  File "/home/ec2-user/exl19/lib/python3.10/site-packages/blessed/terminal.py", line 21, in <module>
    from .keyboard import (_time_left,
  File "/home/ec2-user/exl19/lib/python3.10/site-packages/blessed/keyboard.py", line 19, in <module>
    import curses
  File "/usr/local/lib/python3.10/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by turboderp** [comment]
I'm actually not sure what the deal is there. It looks like a broken dependency in `blessed`? There's some discussion [here](https://github.com/jquast/blessed/issues/215) that may be relevant?

**Comment by rjmehta1993** [comment]
Okay, the problem is with python 3.10. I tried in python3.7 and that worked fine. Thanks.
