### ISSUE TITLE
RuntimeError: start (0) + length (32032) exceeds dimension size (32001).

### ISSUE THREAD

**Issue by Thireus** [turboderp/exllamav2#52]
I am facing the following error (I used commit c0dd3412d59c0bc776264512bf76264e954c221d):
```
 -- Layer: model.norm (RMSNorm)   
 -- Layer rfn_error: 0.000000
 -- Module quantized, time: 281.62 seconds
 -- Layer: lm_head (Linear)
 -- Linear: lm_head -> 0.15:8b/0.85:6b 32g s4, 6.44 bpw
Traceback (most recent call last):
  File "/home/user/exllamav2/convert.py", line 274, in <module>
    quant(job, save_job, model)   
  File "/home/user/exllamav2/conversion/quantize.py", line 679, in quant
    a_ = outputs.narrow(-1, 0, target.shape[-1])
RuntimeError: start (0) + length (32032) exceeds dimension size (32001).
```

I have also tried to pull the latest commit and still face the error (now using commit ee7bf49804bfb53775424d4c12294445497b610f):
```
 -- Target bits per weight: 4.0 (decoder), 6 (head)
 -- Max shard size: 8192 MB
 -- Quantizing...
 -- Layer: lm_head (Linear)
 -- Linear: lm_head -> 0.15:8b/0.85:6b 32g s4, 6.44 bpw
Traceback (most recent call last):
  File "/home/user/exllamav2/convert.py", line 279, in <module>
    quant(job, save_job, model)
  File "/home/user/exllamav2/conversion/quantize.py", line 679, in quant
    a_ = outputs.narrow(-1, 0, target.shape[-1])
RuntimeError: start (0) + length (32032) exceeds dimension size (32001).
```

It looks to me like this is related to  `"vocab_size": 32001`. I didn't face such issue quantizing the model from its FP16 or BF16 versions. This is only happening with the original FP32 version.

**Comment by turboderp** [comment]
Yeah, this is because of a commit I forgot to push. It's not because the input is FP32 but because it uses an extended vocabulary so it has to pad the output layer.

I'm updating it later today, but for now you can make the change to `conversion/quantize.py`, line 679, something like:

```Python
                a_ = outputs.narrow(-1, 0, target.shape[-1])
                b_ = target
```

->

```Python
                dim = min(target.shape[-1], outputs.shape[-1])
                a_ = outputs.narrow(-1, 0, dim)
                b_ = target.narrow(-1, 0, dim)
```

**Comment by Thireus** [comment]
Ah! Thank you, that code change worked. :)
