### ISSUE TITLE
Multicache test falied

### ISSUE THREAD

**Issue by freQuensy23-coder** [turboderp/exllamav2#560]
I've downloaded exllama v2 repo, then run tests/test.py

Simple generation, streaming and batching works well, but batched multi cache falied with error:
```python
Traceback (most recent call last):
  File "C:\Users\alexey\PycharmProjects\exllamav2_lib\tests\test.py", line 254, in <module>
    tests(q_model_directory, False, False)
  File "C:\Users\alexey\PycharmProjects\exllamav2_lib\tests\test.py", line 244, in tests
    if model.is_quant(): test_multicache(40)
                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\PycharmProjects\exllamav2_lib\tests\test.py", line 212, in test_multicache
    logits = model.forward(inputs, caches, input_mask=None).float().cpu()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\anaconda3\envs\py311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\PycharmProjects\exllamav2_lib\exllamav2\model.py", line 750, in forward
    result = self.forward_chunk(input_ids = input_ids,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\anaconda3\envs\py311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\PycharmProjects\exllamav2_lib\exllamav2\model.py", line 916, in forward_chunk
    x = module.forward(x, cache = cache, attn_params = attn_params, past_len = past_len, loras = loras, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\PycharmProjects\exllamav2_lib\exllamav2\attn.py", line 990, in forward
    hidden_states,
    ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'attn_output' where it is not associated with a value
```

Model: TheBloke/Mistral-7B-Instruct-v0.1-GPTQ

**Comment by turboderp** [comment]
Yeah, that test script is out of date. Multiple caches is redundant now so I removed the feature, but I neglected to update/remove the test.
