### ISSUE TITLE
MemoryError despite sufficient system resources

### ISSUE THREAD

**Issue by KingBipo** [turboderp/exllamav2#596]
I'm encountering a `MemoryError` while running ExLlamaV2Config(), even though my system's memory usage is not close to being full. Here are the details of my setup and the error:

**System Configuration:**
- GPU: NVIDIA A4000
- RAM: 64 GB
- CUDA Version: 12.1
- PyTorch Version: 2.2.2 with CUDA 12.1

**Error Log:**
```
Traceback (most recent call last):
  File "/home/usr/myProject-llm/python/mainLLM.py", line 75, in <module>
    main()
  File "/home/usr/myProject-llm/python/mainLLM.py", line 26, in main
    config = ExLlamaV2Config(r"../models/Meta-Llama-3-8B-Instruct-4.0bpw-h6-exl2")
  File "/home/usr/anaconda3/envs/loadModel/lib/python3.10/site-packages/exllamav2/config.py", line 145, in __init__
    self.prepare()
  File "/home/usr/anaconda3/envs/loadModel/lib/python3.10/site-packages/exllamav2/config.py", line 326, in prepare
    f = STFile.open(st_file, fast = self.fasttensors, keymap = self.arch.keymap)
  File "/home/usr/anaconda3/envs/loadModel/lib/python3.10/site-packages/exllamav2/fasttensors.py", line 126, in open
    return STFile(filename, fast, keymap)
  File "/home/usr/anaconda3/envs/loadModel/lib/python3.10/site-packages/exllamav2/fasttensors.py", line 69, in __init__
    self.read_dict()
  File "/home/usr/anaconda3/envs/loadModel/lib/python3.10/site-packages/exllamav2/fasttensors.py", line 140, in read_dict
    header_json = fp.read(header_size)
MemoryError
```

The available RAM is not nearly utilized during execution.
The GPU memory is also not at full capacity.

**Comment by turboderp** [comment]
It looks like you have a corrupted .safetensors file. Could you verify the checksum with the HF repo?

**Comment by KingBipo** [comment]
Yes thank you for the fast reply. This was the case.
