### ISSUE TITLE
Convert script fails

### ISSUE THREAD

**Issue by epicfilemcnulty** [turboderp/exllamav2#6]
Trying to convert a couple of models, getting two different errors:

```
python convert.py -i /storage/models/LLaMA/FP16/CodeLlama-7B -o out -c ~/Downloads/wikitext-103-raw-v1/0000.parquet -b 6
 -- Beginning new job
 -- Input: /storage/models/LLaMA/FP16/CodeLlama-7B
 -- Output: /home/epicfile/deviant/ai/llm/exllamav2/out
 -- Calibration dataset: /home/epicfile/Downloads/wikitext-103-raw-v1/0000.parquet, 100 / 16 (16) rows, 2048 tokens per sample
 -- Target bits per weight: 6.0 (decoder), 6 (head)
 -- Tokenizing samples (measurement)...
 -- Token embeddings (measurement)...
Traceback (most recent call last):
  File "/home/epicfile/deviant/ai/llm/exllamav2/convert.py", line 161, in <module>
    embeddings(job, save_job, model)
  File "/home/epicfile/deviant/ai/llm/exllamav2/conversion/quantize.py", line 45, in embeddings
    hidden_state = module.forward(input_ids)
  File "/home/epicfile/deviant/ai/llm/exllamav2/exllamav2/embedding.py", line 66, in forward
    hidden_states = self.embedding.forward(hidden_states)
  File "/home/epicfile/.venvs/lasta/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/epicfile/.venvs/lasta/lib/python3.10/site-packages/torch/nn/functional.py", line 2238, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)
```

```
python convert.py -i /storage/models/LLaMA/FP16/Synthia-13B -o out -c ~/Downloads/wikitext-103-raw-v1/0000.parquet -b 6 
Traceback (most recent call last):
  File "/home/epicfile/deviant/ai/llm/exllamav2/convert.py", line 53, in <module>
    model.load(lazy = True)
  File "/home/epicfile/deviant/ai/llm/exllamav2/exllamav2/model.py", line 227, in load
    stats = self.set_device_map(gpu_split or [99999])
  File "/home/epicfile/deviant/ai/llm/exllamav2/exllamav2/model.py", line 185, in set_device_map
    footprint = module.weight_footprint()   # Footprint, in bytes
  File "/home/epicfile/deviant/ai/llm/exllamav2/exllamav2/attn.py", line 109, in weight_footprint
    self.q_proj.weight_footprint() + \
  File "/home/epicfile/deviant/ai/llm/exllamav2/exllamav2/module.py", line 118, in weight_footprint
    else: raise ValueError("Unknown tensor type: " + self.key)
ValueError: Unknown tensor type: model.layers.0.self_attn.q_proj
```

**Comment by turboderp** [comment]
The first one is very weird. Some problem with the tokenizer, it looks like? I can't look at it right now though, but that's what I'd assume.

For the second one I'm guessing you don't have a .safetensors version of the weights. (?) The conversion only works with safetensors as an input.

**Comment by ardfork** [comment]
I have the same issue as the first one when trying to run perplexity using `python test_inference.py -m GPTQ-model 0000.parquet`. I download the .parquet here: https://huggingface.co/datasets/wikitext/tree/refs%2Fconvert%2Fparquet/wikitext-2-raw-v1/train

**Comment by turboderp** [comment]
It looks like that Parquet file starts with an empty row, which SentencePiece turns into an empty tensor without a datatype, so it becomes float by default and and int64 tensors concatenated to it subsequently are converted to float as well. What a fun bug.

Anyway, it should be fixed with the latest commit.

**Comment by epicfilemcnulty** [comment]
@turboderp yep, you were right about the second one, no safetensors.
and yes, the first one is fixed with the latest commit, thank you!
btw, what datasests would you recommend for conversion?

**Comment by epicfilemcnulty** [comment]
hmm, got a new error though, running
`python convert.py -i /storage/models/LLaMA/FP16/CodeLlama-13B -o out -c ~/Downloads/wikitext-103-raw-v1/0001.parquet -b 6`

```
-- Linear: lm_head -> 0.15:8b/0.85:6b 32g s4, 6.43 bpw
 !! Note: Padding quantized tensor lm_head
Traceback (most recent call last):
  File "/home/epicfile/deviant/ai/llm/exllamav2/convert.py", line 195, in <module>
    quant(job, save_job, model)
  File "/home/epicfile/deviant/ai/llm/exllamav2/conversion/quantize.py", line 508, in quant
    do_quant(module, [input_states], qp.get_dict(), job)
  File "/home/epicfile/deviant/ai/llm/exllamav2/conversion/quantize.py", line 392, in do_quant
    diff1 = torch.max(torch.abs(quant_w - recons_w))
RuntimeError: The size of tensor a (32016) must match the size of tensor b (32032) at non-singleton dimension 1
```

**Comment by epicfilemcnulty** [comment]
Very strange, I've tried converting both CodeLLama-7B and 13B, using wikitext-1/2, and everytime I get this error:
```
-- Layer: model.norm (RMSNorm)
 -- Layer rfn_error: 0.000000
 -- Layer: lm_head (Linear)
 -- Linear: lm_head -> 0.15:8b/0.85:6b 32g s4, 6.44 bpw
 !! Note: Padding quantized tensor lm_head
Traceback (most recent call last):
  File "/home/epicfile/deviant/ai/llm/exllamav2/convert.py", line 195, in <module>
    quant(job, save_job, model)
  File "/home/epicfile/deviant/ai/llm/exllamav2/conversion/quantize.py", line 508, in quant
    do_quant(module, [input_states], qp.get_dict(), job)
  File "/home/epicfile/deviant/ai/llm/exllamav2/conversion/quantize.py", line 392, in do_quant
    diff1 = torch.max(torch.abs(quant_w - recons_w))
RuntimeError: The size of tensor a (32016) must match the size of tensor b (32032) at non-singleton dimension 1
```

However, I was able to successfully convert other Llama-2 based models.

**Comment by turboderp** [comment]
Hmm, I thought I fixed that. It's CodeLlama 13B, specifically, being weird with its extended vocabulary. It's supposed to pad the quantized tensor, but apparently it's not very good at that. I'll have to go over it again, but don't delete the output folder in the meantime. You should still be able to resume the job once I figure this out.

**Comment by ashwincc** [comment]
Hi i had the same second issue while converting. Tried the hugging face conversion again with safetensor flag.
meta-llam2 -> hf: 
``
python src/transformers/models/llama/convert_llama_weights_to_hf.py     --input_dir ../llama/llama-2-7b/ --model_size 7B --output_dir ../llama/meta2hf/ --safe_serialization true``

After this i tried the exllama conversion script:
``
python convert.py -i ./model/llama2-7b/ -o ./model/converted/ -b 8  ``



Hi i had the same second issue while converting. Tried the hugging face conversion again with safetensor flag.
meta-llam2 -> hf: 

python src/transformers/models/llama/convert_llama_weights_to_hf.py     --input_dir ../llama/llama-2-7b/ --model_size 7B --output_dir ../llama/meta-hf/ --safe_serialization true``

After this i tried the exllama conversion script:
``
python convert.py -i ./model/llama2-7b/ -o ./model/converted/ -b 8  
``

Traceback (most recent call last):
  File "/home/jordan/git_repos/exllamav2/convert.py", line 53, in <module>
    model.load(lazy = True)
  File "/home/exllamav2/exllamav2/model.py", line 227, in load
    stats = self.set_device_map(gpu_split or [99999])
  File "/home/exllamav2/exllamav2/model.py", line 185, in set_device_map
    footprint = module.weight_footprint()   # Footprint, in bytes
  File "/home/exllamav2/exllamav2/attn.py", line 109, in weight_footprint
    self.q_proj.weight_footprint() + \
  File "/home/exllamav2/exllamav2/module.py", line 114, in weight_footprint
    self.footprint = self.load_multi(["weight"], measure = True)
  File "/home/exllamav2/exllamav2/module.py", line 67, in load_multi
    size += _tsize(st, self.key + "." + k)
  File "/home/exllamav2/exllamav2/module.py", line 23, in _tsize
    else: raise ValueError(f"Unexpected datatype {dtype}: {key}")
ValueError: Unexpected datatype BF16: model.layers.0.self_attn.q_proj.weight

**Comment by turboderp** [comment]
The convert script should now correctly handle the extended vocabulary of CodeLlama-13B. Mystery now is why 34B doesn't use the same vocabulary.

I'll get to the BF16 models soon.

**Comment by turboderp** [comment]
I'll assume this is fixed for now. Feel free to reopen otherwise.
