### ISSUE TITLE
[BUG] 0.2.1 doesn't compile on Opensuse

### ISSUE THREAD

**Issue by avidwriter** [turboderp/exllamav2#620]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.11

### Pytorch version

0

### Describe the bug

compile fails on opensuse

### Reproduction steps

pip install .

### Expected behavior

compiles w no error

### Logs

```
(exllama) xx@localhost:~/exllamav2> pip install -r requirements.txt
Requirement already satisfied: pandas in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: ninja in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 2)) (1.11.1.1)
Requirement already satisfied: wheel in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 3)) (0.44.0)
Requirement already satisfied: setuptools in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 4)) (65.5.0)
Requirement already satisfied: fastparquet in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 5)) (2024.5.0)
Requirement already satisfied: torch>=2.2.0 in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 6)) (2.4.0)
Requirement already satisfied: safetensors>=0.4.3 in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 7)) (0.4.4)
Requirement already satisfied: sentencepiece>=0.1.97 in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 8)) (0.2.0)
Requirement already satisfied: pygments in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 9)) (2.18.0)
Requirement already satisfied: websockets in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 10)) (13.0)
Requirement already satisfied: regex in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 11)) (2024.7.24)
Requirement already satisfied: numpy~=1.26.4 in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 12)) (1.26.4)
Requirement already satisfied: tokenizers in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 13)) (0.20.0)
Requirement already satisfied: rich in /home/xx/exllama/lib64/python3.11/site-packages (from -r requirements.txt (line 14)) (13.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/xx/exllama/lib64/python3.11/site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/xx/exllama/lib64/python3.11/site-packages (from pandas->-r requirements.txt (line 1)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/xx/exllama/lib64/python3.11/site-packages (from pandas->-r requirements.txt (line 1)) (2024.1)
Requirement already satisfied: cramjam>=2.3 in /home/xx/exllama/lib64/python3.11/site-packages (from fastparquet->-r requirements.txt (line 5)) (2.8.3)
Requirement already satisfied: fsspec in /home/xx/exllama/lib64/python3.11/site-packages (from fastparquet->-r requirements.txt (line 5)) (2024.6.1)
Requirement already satisfied: packaging in /home/xx/exllama/lib64/python3.11/site-packages (from fastparquet->-r requirements.txt (line 5)) (24.1)
Requirement already satisfied: filelock in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (4.12.2)
Requirement already satisfied: sympy in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (1.13.2)
Requirement already satisfied: networkx in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (3.3)
Requirement already satisfied: jinja2 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->-r requirements.txt (line 6)) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/xx/exllama/lib64/python3.11/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.2.0->-r requirements.txt (line 6)) (12.6.20)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /home/xx/exllama/lib64/python3.11/site-packages (from tokenizers->-r requirements.txt (line 13)) (0.24.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/xx/exllama/lib64/python3.11/site-packages (from rich->-r requirements.txt (line 14)) (3.0.0)
Requirement already satisfied: pyyaml>=5.1 in /home/xx/exllama/lib64/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers->-r requirements.txt (line 13)) (6.0.2)
Requirement already satisfied: requests in /home/xx/exllama/lib64/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers->-r requirements.txt (line 13)) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /home/xx/exllama/lib64/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers->-r requirements.txt (line 13)) (4.66.5)
Requirement already satisfied: mdurl~=0.1 in /home/xx/exllama/lib64/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->-r requirements.txt (line 14)) (0.1.2)
Requirement already satisfied: six>=1.5 in /home/xx/exllama/lib64/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/xx/exllama/lib64/python3.11/site-packages (from jinja2->torch>=2.2.0->-r requirements.txt (line 6)) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/xx/exllama/lib64/python3.11/site-packages (from sympy->torch>=2.2.0->-r requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/xx/exllama/lib64/python3.11/site-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers->-r requirements.txt (line 13)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/xx/exllama/lib64/python3.11/site-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers->-r requirements.txt (line 13)) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/xx/exllama/lib64/python3.11/site-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers->-r requirements.txt (line 13)) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/xx/exllama/lib64/python3.11/site-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers->-r requirements.txt (line 13)) (2024.7.4)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
(exllama) xx@localhost:~/exllamav2> pip install .
Processing /home/xx/exllamav2
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (2.2.2)
Requirement already satisfied: ninja in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (1.11.1.1)
Requirement already satisfied: fastparquet in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (2024.5.0)
Requirement already satisfied: torch>=2.2.0 in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (2.4.0)
Requirement already satisfied: safetensors>=0.3.2 in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (0.4.4)
Requirement already satisfied: sentencepiece>=0.1.97 in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (0.2.0)
Requirement already satisfied: pygments in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (2.18.0)
Requirement already satisfied: websockets in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (13.0)
Requirement already satisfied: regex in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (2024.7.24)
Requirement already satisfied: numpy in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (1.26.4)
Requirement already satisfied: rich in /home/xx/exllama/lib64/python3.11/site-packages (from exllamav2==0.2.1) (13.7.1)
Requirement already satisfied: filelock in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (4.12.2)
Requirement already satisfied: sympy in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (1.13.2)
Requirement already satisfied: networkx in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (3.3)
Requirement already satisfied: jinja2 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (3.1.4)
Requirement already satisfied: fsspec in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /home/xx/exllama/lib64/python3.11/site-packages (from torch>=2.2.0->exllamav2==0.2.1) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/xx/exllama/lib64/python3.11/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.2.0->exllamav2==0.2.1) (12.6.20)
Requirement already satisfied: cramjam>=2.3 in /home/xx/exllama/lib64/python3.11/site-packages (from fastparquet->exllamav2==0.2.1) (2.8.3)
Requirement already satisfied: packaging in /home/xx/exllama/lib64/python3.11/site-packages (from fastparquet->exllamav2==0.2.1) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/xx/exllama/lib64/python3.11/site-packages (from pandas->exllamav2==0.2.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/xx/exllama/lib64/python3.11/site-packages (from pandas->exllamav2==0.2.1) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/xx/exllama/lib64/python3.11/site-packages (from pandas->exllamav2==0.2.1) (2024.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/xx/exllama/lib64/python3.11/site-packages (from rich->exllamav2==0.2.1) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in /home/xx/exllama/lib64/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->exllamav2==0.2.1) (0.1.2)
Requirement already satisfied: six>=1.5 in /home/xx/exllama/lib64/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->exllamav2==0.2.1) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/xx/exllama/lib64/python3.11/site-packages (from jinja2->torch>=2.2.0->exllamav2==0.2.1) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/xx/exllama/lib64/python3.11/site-packages (from sympy->torch>=2.2.0->exllamav2==0.2.1) (1.3.0)
Building wheels for collected packages: exllamav2
  Building wheel for exllamav2 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [634 lines of output]
      Version: 0.2.1
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching 'dni_*' found anywhere in distribution
      /home/xx/exllama/lib64/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'exllamav2.conversion' as data is deprecated, please list it in `packages`.
          !!
      
...
      

      [27/48] c++ -MMD -MF /home/xx/exllamav2/build/temp.linux-x86_64-cpython-311/exllamav2/exllamav2_ext/cpp/safetensors.o.d -Wsign-compare -DNDEBUG -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -IVendor/ -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -IVendor/ -fPIC -I/home/xx/exllama/lib64/python3.11/site-packages/torch/include -I/home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/xx/exllama/lib64/python3.11/site-packages/torch/include/TH -I/home/xx/exllama/lib64/python3.11/site-packages/torch/include/THC -I/usr/local/cuda-12.6/include -I/home/xx/exllama/include -I/usr/include/python3.11 -c -c /home/xx/exllamav2/exllamav2/exllamav2_ext/cpp/safetensors.cpp -o /home/xx/exllamav2/build/temp.linux-x86_64-cpython-311/exllamav2/exllamav2_ext/cpp/safetensors.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=exllamav2_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      In file included from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/IListRef.h:631,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/WrapDimUtils.h:3,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/TensorNames.h:3,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/NamedTensorUtils.h:3,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/csrc/autograd/variable.h:11,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/extension.h:5,
                       from /home/xx/exllamav2/exllamav2/exllamav2_ext/cpp/safetensors.h:4,
                       from /home/xx/exllamav2/exllamav2/exllamav2_ext/cpp/safetensors.cpp:1:
      /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/IListRef_inl.h: In static member function ‘static c10::detail::IListRefConstRef<at::OptionalTensorRef> c10::detail::IListRefTagImpl<c10::IListRefTag::Boxed, at::OptionalTensorRef>::iterator_get(const c10::List<std::optional<at::Tensor> >::const_iterator&)’:
      /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/IListRef_inl.h:171:17: warning: possibly dangling reference to a temporary [-Wdangling-reference]
        171 |     const auto& ivalue = (*it).get();
            |                 ^~~~~~
      /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/IListRef_inl.h:171:35: note: the temporary was destroyed at the end of the full expression ‘(& it)->c10::impl::ListIterator<std::optional<at::Tensor>, __gnu_cxx::__normal_iterator<c10::IValue*, std::vector<c10::IValue> > >::operator*().c10::impl::ListElementReference<std::optional<at::Tensor>, __gnu_cxx::__normal_iterator<c10::IValue*, std::vector<c10::IValue> > >::get()’
        171 |     const auto& ivalue = (*it).get();
            |                          ~~~~~~~~~^~
      In file included from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/dispatch/OperatorEntry.h:12,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:6,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/library.h:63,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/csrc/autograd/autograd_not_implemented_fallback.h:3,
                       from /home/xx/exllama/lib64/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:4:
      /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/dispatch/DispatchKeyExtractor.h: In lambda function:
      /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/dispatch/DispatchKeyExtractor.h:154:32: warning: possibly dangling reference to a temporary [-Wdangling-reference]
        154 |         for (const at::Tensor& tensor : ivalue.toTensorList()) {
            |                                ^~~~~~
      /home/xx/exllama/lib64/python3.11/site-packages/torch/include/ATen/core/dispatch/DispatchKeyExtractor.h:154:61: note: the temporary was destroyed at the end of the full expression ‘__for_begin .c10::impl::ListIterator<at::Tensor, __gnu_cxx::__normal_iterator<c10::IValue*, std::vector<c10::IValue> > >::operator*().c10::impl::ListElementReference<at::Tensor, __gnu_cxx::__normal_iterator<c10::IValue*, std::vector<c10::IValue> > >::operator std::conditional_t<true, const at::Tensor&, at::Tensor>()’
        154 |         for (const at::Tensor& tensor : ivalue.toTensorList()) {
            |                                                             ^
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/xx/exllama/lib64/python3.11/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
          subprocess.run(
        File "/usr/lib64/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/xx/exllamav2/setup.py", line 97, in <module>
          setup(
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/xx/exllama/lib64/python3.11/site-packages/wheel/_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/xx/exllama/lib64/python3.11/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
          build_ext.build_extensions(self)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/xx/exllama/lib64/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/xx/exllama/lib64/python3.11/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/xx/exllama/lib64/python3.11/site-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/xx/exllama/lib64/python3.11/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for exllamav2
  Running setup.py clean for exllamav2
Failed to build exllamav2
ERROR: Could not build wheels for exllamav2, which is required to install pyproject.toml-based projects
```

### Additional context

0.2.0 works

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
Whatever the error is it happens during the build, so somewhere in the part you snipped out should be an error message. It's always a wall of text, sadly, but I need the whole thing to be able to say what's up.

**Comment by avidwriter** [comment]
sorry github wouldnt let me paste it all in. here you go https://pastebin.com/6hRWBUXi

**Comment by turboderp** [comment]
Okay, nw. The error is here:

```
error: #error -- unsupported GNU version! gcc versions later than 13 are not supported!
```

It looks like you've also managed to update gcc along the way, or you've lost gcc-13 somehow. There are supposed to be symlinks in your $CUDA_HOME/bin folder pointing to gcc-13 and g++-13. Not sure if that's a separate package on OpenSUSE

**Comment by avidwriter** [comment]
looks like i have 13 and 14 installed, trying to remove the 14 packages would uninstall all the nvidia software. wonder why 0.2.0 works

**Comment by turboderp** [comment]
Make sure those symlinks are correct. E.g. `$CUDA_HOME/bin/gcc --version`

**Comment by avidwriter** [comment]
yeah i dont have $cuda_home defined

**Comment by avidwriter** [comment]
thanks this worked `sudo ln -s /usr/bin/gcc-13 /usr/local/cuda/bin/gcc`
