### ISSUE TITLE
[BUG] Out of memory on dual 3090 setup

### ISSUE THREAD

**Issue by joshuakoh1** [turboderp/exllamav2#663]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.11

### Pytorch version

2.4.1+cu121

### Describe the bug

Running out of memory when loading large model in dual GPU setup. Tried auto split as well as manual split [20,24]

### Reproduction steps

Load model

### Expected behavior

Model should have been offloaded across both GPUs with enough memory

### Logs

```INFO:     127.0.0.1:65376 - "POST /v1/model/load HTTP/1.1" 200
INFO:     Unloading existing model.
INFO:     Model unloaded.
WARNING:  The given cache_size (4096) is less than 2 * max_seq_len and may be too small for requests using CFG.
WARNING:  Ignore this warning if you do not plan on using CFG.
INFO:     Attempting to load a prompt template if present.
INFO:     Using template "from_tokenizer_config" for chat completions.
INFO:     Loading draft model: C:\Users\Joshua\Downloads\tabbyAPI\models\Llama-3.1-Nemotron-70B-Instruct-HF-exl2-3.0
INFO:     Loading model: C:\Users\Joshua\Downloads\tabbyAPI\models\Llama-3.1-Nemotron-70B-Instruct-HF-exl2-3.0
INFO:     Loading with a manual GPU split (or a one GPU setup)
Loading draft modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 163/163 0:00:00
Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   1%   1/163 -:--:--
ERROR:    Traceback (most recent call last):
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\endpoints\core\utils\model.py", line 113, in stream_model_load
ERROR:        async for module, modules, model_type in load_status:
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\common\model.py", line 80, in load_model_gen
ERROR:        async for module, modules in load_status:
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\backends\exllamav2\model.py", line 538, in load_gen
ERROR:        async for value in iterate_in_threadpool(model_load_generator):
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\common\concurrency.py", line 30, in iterate_in_threadpool
ERROR:        yield await asyncio.to_thread(gen_next, generator)
ERROR:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\AppData\Local\Programs\Python\Python311\Lib\asyncio\threads.py", line 25, in to_thread
ERROR:        return await loop.run_in_executor(None, func_call)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in
run
ERROR:        result = self.fn(*self.args, **self.kwargs)
ERROR:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\common\concurrency.py", line 20, in gen_next
ERROR:        return next(generator)
ERROR:               ^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\venv\Lib\site-packages\torch\utils\_contextlib.py", line 57, in
generator_context
ERROR:        response = gen.send(request)
ERROR:                   ^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\backends\exllamav2\model.py", line 639, in load_model_sync
ERROR:        for value in self.model.load_gen(
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\venv\Lib\site-packages\exllamav2\model.py", line 315, in load_gen
ERROR:        module.load()
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in
decorate_context
ERROR:        return func(*args, **kwargs)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\venv\Lib\site-packages\exllamav2\attn.py", line 224, in load
ERROR:        self.q_proj.load(device_context = device_context)
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in
decorate_context
ERROR:        return func(*args, **kwargs)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\venv\Lib\site-packages\exllamav2\linear.py", line 137, in load
ERROR:        device_context = self.model.get_device_context(self.device_idx)
ERROR:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\venv\Lib\site-packages\exllamav2\model.py", line 712, in
get_device_context
ERROR:        if not context.ready: context.prepare(scratch)
ERROR:                              ^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\Joshua\Downloads\tabbyAPI\venv\Lib\site-packages\exllamav2\device.py", line 78, in prepare
ERROR:        self.scratch = torch.empty((self.scratch_bytes // 2,), dtype = torch.half, device =
_torch_device(self.device_idx))
ERROR:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:    torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 706.00 MiB. GPU 0 has a total capacity of 24.00
GiB of which 0 bytes is free. Of the allocated memory 22.68 GiB is allocated by PyTorch, and 204.70 MiB is reserved by
PyTorch but unallocated. If reserved but unallocated memory is large try setting
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR:    Sent to request: CUDA out of memory. Tried to allocate 706.00 MiB. GPU 0 has a total capacity of 24.00 GiB of
which 0 bytes is free. Of the allocated memory 22.68 GiB is allocated by PyTorch, and 204.70 MiB is reserved by PyTorch
but unallocated. If reserved but unallocated memory is large try setting
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)```

### Additional context

_No response_

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by DocShotgun** [comment]
>```
>INFO:     Loading draft model: C:\Users\Joshua\Downloads\tabbyAPI\models\Llama-3.1-Nemotron-70B-Instruct-HF-exl2-3.0
>INFO:     Loading model: C:\Users\Joshua\Downloads\tabbyAPI\models\Llama-3.1-Nemotron-70B-Instruct-HF-exl2-3.0
>```

Sir you are trying to load 2 full 70B models simultaneously.

**Comment by joshuakoh1** [comment]
> > ```
> > INFO:     Loading draft model: C:\Users\Joshua\Downloads\tabbyAPI\models\Llama-3.1-Nemotron-70B-Instruct-HF-exl2-3.0
> > INFO:     Loading model: C:\Users\Joshua\Downloads\tabbyAPI\models\Llama-3.1-Nemotron-70B-Instruct-HF-exl2-3.0
> > ```
> 
> Sir you are trying to load 2 full 70B models simultaneously.

Thank you! That makes so much sense. New to the loader I'm using and didn't realise draft model and model was a different thing. Is there a difference on whether I load it as a draft?
