### ISSUE TITLE
[BUG]  QVQ 72B Preview multimodality crash

### ISSUE THREAD

**Issue by ThomasBaruzier** [turboderp/exllamav2#705]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.13

### Pytorch version

2.5.1

### Model

Qwen/QVQ-72B-Preview

### Describe the bug

 QVQ 72B Preview multimodality crashes

Config:
```yaml
model:
  model_dir: exl
  inline_model_loading: false
  use_dummy_models: false
  model_name: QVQ-72B-Preview-4.0bpw
  use_as_default: ['max_seq_len', 'cache_mode', 'chunk_size']
  max_seq_len: 32768
  tensor_parallel: false
  gpu_split_auto: false
  autosplit_reserve: [0]
  gpu_split: [17,25]
  rope_scale: 1.0
  rope_alpha: 1.0
  cache_mode: Q6
  cache_size:
  chunk_size: 2048
  max_batch_size:
  prompt_template:
  vision: true
  num_experts_per_token:

draft_model:
  draft_model_name: Qwen2.5-Coder-1.5B-Instruct-6.0bpw
  draft_rope_scale: 1.0
  draft_rope_alpha: 1.0
  draft_cache_mode: Q6
```

### Reproduction steps

Send image

### Expected behavior

Read image

### Logs

```python
INFO:     127.0.0.1:59044 - "POST /v1/chat/completions HTTP/1.1" 200
INFO:     Received chat completion streaming request 9fa9aab66f344274a8f8375b1392ab63
WARNING:  Temperature is set to 0. Overriding temp, top_k, top_p, and typical to 1.0, 1, 0, and 0.
ERROR:    FATAL ERROR with generation. Attempting to recreate the generator. If this fails, please restart the server.

WARNING:  Immediately terminating all jobs. Clients will have their requests cancelled.

ERROR:    Traceback (most recent call last):
ERROR:      File "/home/user/files/ai/tabby/endpoints/OAI/utils/chat_completion.py", line 357, in stream_generate_chat_completion
ERROR:        raise generation
ERROR:      File "/home/user/files/ai/tabby/endpoints/OAI/utils/completion.py", line 100, in _stream_collector
ERROR:        async for generation in new_generation:
ERROR:        ...\<5 lines>...
ERROR:                break
ERROR:      File "/home/user/files/ai/tabby/backends/exllamav2/model.py", line 1453, in generate_gen
ERROR:        raise ex
ERROR:      File "/home/user/files/ai/tabby/backends/exllamav2/model.py", line 1361, in generate_gen
ERROR:        async for result in job:
ERROR:        ...\<76 lines>...
ERROR:                    break
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/exllamav2/generator/dynamic_async.py", line 97, in __aiter__
ERROR:        raise result
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/exllamav2/generator/dynamic_async.py", line 28, in _run_iteration
ERROR:        results = self.generator.iterate()
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR:        return func(*args, **kwargs)
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/exllamav2/generator/dynamic.py", line 971, in iterate
ERROR:        job.prefill(results)
ERROR:        ~~~~~~~~~~~^^^^^^^^^
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/exllamav2/generator/dynamic.py", line 2412, in prefill
ERROR:        self.generator.draft_model.forward_chunk(
ERROR:        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
ERROR:            input_ids = prefill_ids,
ERROR:            ^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:        ...\<2 lines>...
ERROR:            cache = self.generator.draft_cache,
ERROR:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:        )
ERROR:        ^
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR:        return func(*args, **kwargs)
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/exllamav2/model.py", line 1010, in forward_chunk
ERROR:        x = module.forward(x, cache = cache, attn_params = attn_params, past_len = past_len, loras = loras, **kwargs)
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/exllamav2/embedding.py", line 182, in forward
ERROR:        hidden_states = self.embedding(hidden_states)
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR:        return self._call_impl(*args, **kwargs)
ERROR:               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR:        return forward_call(*args, **kwargs)
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/torch/nn/modules/sparse.py", line 190, in forward
ERROR:        return F.embedding(
ERROR:               ~~~~~~~~~~~^
ERROR:            input,
ERROR:            ^^^^^^
ERROR:        ...\<5 lines>...
ERROR:            self.sparse,
ERROR:            ^^^^^^^^^^^^
ERROR:        )
ERROR:        ^
ERROR:      File "/home/user/files/ai/tabby/.venv/lib/python3.13/site-packages/torch/nn/functional.py", line 2551, in embedding
ERROR:        return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
ERROR:               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:    IndexError: index out of range in self
ERROR:    Sent to request: Chat completion aborted. Please check the server console.
```

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
You won't be able to use a draft model with a vision model. There are no facilities at the moment for dealing with the vision tokens in the draft model, even if the draft model had a vision adapter (which 2.5-coder doesn't).

**Comment by ThomasBaruzier** [comment]
Removing the draft model fixed the issue. Thanks
