### ISSUE TITLE
test_inference.py : AttributeError: module 'exllamav2_ext' has no attribute 'rms_norm'

### ISSUE THREAD

**Issue by DFuller134** [turboderp/exllamav2#92]
```
root@0d4e7b58dda1:/exllamav2# PYTHONPATH=exllamav2 python test_inference.py -m /model -p "Once upon a time,"
 -- Model: /model
 -- Options: ['rope_scale 1.0', 'rope_alpha 1.0']
 -- Loading model...
 -- Loading tokenizer...
 -- Warmup...
Traceback (most recent call last):
  File "/exllamav2/test_inference.py", line 62, in <module>
    generator.warmup()
  File "/exllamav2/exllamav2/generator/base.py", line 36, in warmup
    self.model.forward(input_ids, cache = None, input_mask = None, preprocess_only = True)
  File "/exllamav2/exllamav2/model.py", line 330, in forward
    return self._forward(input_ids = input_ids,
  File "/exllamav2/exllamav2/model.py", line 422, in _forward
    x = module.forward(x, cache = cache, attn_mask = attn_mask, past_len = past_len)
  File "/exllamav2/exllamav2/attn.py", line 213, in forward
    return self.forward_torch(hidden_states, cache, attn_mask, past_len, intermediates)
  File "/exllamav2/exllamav2/attn.py", line 433, in forward_torch
    post_norm = self.input_layernorm.forward(hidden_states)
  File "/exllamav2/exllamav2/rmsnorm.py", line 58, in forward
    ext_c.rms_norm(hidden_states, self.weight, norm, self.variance_epsilon)
AttributeError: module 'exllamav2_ext' has no attribute 'rms_norm'
```

**Comment by turboderp** [comment]
Could you describe the setup a bit more? Is this NVIDIA/AMD, are you using a prebuilt wheel, etc..

**Comment by DFuller134** [comment]
NVIDIA CUDA 11.7

This error resulted from attempting the first How-to example in the README document. So working with a cloned repo.

<img width="590" alt="CleanShot 2023-10-06 at 08 01 41@2x" src="https://github.com/turboderp/exllamav2/assets/15822729/5c40c749-09b1-4cf8-9130-7d556969f9cd">

**Comment by turboderp** [comment]
Best guess is it failed to build the extension for some reason, and left you with an empty module. You can try deleting the directory in `~/.cache/torch_extensions` to force it to rebuild the extensions, and if that still fails there are also the prebuilt wheels on the releases page.

**Comment by DFuller134** [comment]
Unfortunately, clearing the torch_extensions cache did not fix the issue.

Additional notes: I am using PyTorch 2.0.1 which is compatible with my NVIDIA driver 515.48.07 and CUDA 11.7.

**Comment by turboderp** [comment]
And you're not getting compilation errors when you run it? That would suggest maybe there's already a package installed with the same name. Although what that would be, I don't know. The `rms_norm` function should be there even in some very old versions.

What do you get from `pip freeze | grep exllamav2`?

**Comment by DFuller134** [comment]
No compilation errors. Just the missing rms_norm error.

I tried it both ways, with and without the exllamav2 package installed (in virtual env) since I thought maybe there was something that needed to be pre-compiled. Same result.

```
(venv) streamedge@toaster:~/projects/LLM/exllamav2$ pip freeze
cmake==3.27.6
cramjam==2.7.0
fastparquet==2023.8.0
filelock==3.12.4
fsspec==2023.9.2
Jinja2==3.1.2
lit==17.0.2
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.1
ninja==1.11.1
numpy==1.24.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.2
pandas==2.0.3
Pygments==2.16.1
python-dateutil==2.8.2
pytz==2023.3.post1
safetensors==0.4.0
sentencepiece==0.1.99
six==1.16.0
sympy==1.12
torch==2.0.1
triton==2.0.0
typing-extensions==4.8.0
tzdata==2023.3
websockets==11.0.3
```

**Comment by turboderp** [comment]
I'm a little stumped. What Python version are you running?

**Comment by DFuller134** [comment]
Python 3.9.18

So, here's some insight into what's happening in ext.py:

The `import exllamav2_ext` statement executes successfully, but there is no python code to import in that directory, only C. So then what follows is `ext_c = exllamav2_ext` and then the statement that fails `ext_c.rms_norm(hidden_states, self.weight, norm, self.variance_epsilon)`

Inspection of `ext_c` reveals:

```
[('__doc__', None), ('__file__', None), ('__loader__', <_frozen_importlib_external._NamespaceLoader object at 0x7f96cf9bd970>), ('__name__', 'exllamav2_ext'), ('__package__', 'exllamav2_ext'), ('__path__', _NamespacePath(['/home/streamedge/projects/LLM/exllamav2/exllamav2/exllamav2_ext'])), ('__spec__', ModuleSpec(name='exllamav2_ext', loader=<_frozen_importlib_external._NamespaceLoader object at 0x7f96cf9bd970>, submodule_search_locations=_NamespacePath(['/home/streamedge/projects/LLM/exllamav2/exllamav2/exllamav2_ext'])))]
```


ext.py
```
import torch
from torch.utils.cpp_extension import load
import os
import sys
import platform

extension_name = "exllamav2_ext"
verbose = False
ext_debug = False

windows = (os.name == "nt")

try:
    import exllamav2_ext
except ModuleNotFoundError:
    # Kludge to get compilation working on Windows

    if windows:

        def find_msvc():

            # Possible locations for MSVC, in order of preference

            program_files_x64 = os.environ["ProgramW6432"]
            program_files_x86 = os.environ["ProgramFiles(x86)"]

            msvc_dirs = \
            [
                a + "\\Microsoft Visual Studio\\" + b + "\\" + c + "\\VC\Tools\\MSVC\\"
                for b in ["2022", "2019", "2017"]
                for a in [program_files_x64, program_files_x86]
                for c in ["BuildTools", "Community", "Professional", "Enterprise", "Preview"]
            ]

            for msvc_dir in msvc_dirs:
                if not os.path.exists(msvc_dir): continue

                # Prefer the latest version

                versions = sorted(os.listdir(msvc_dir), reverse = True)
                for version in versions:

                    compiler_dir = msvc_dir + version + "\\bin\\Hostx64\\x64"
                    if os.path.exists(compiler_dir) and os.path.exists(compiler_dir + "\\cl.exe"):
                        return compiler_dir

            # No path found

            return None

        import subprocess

        # Check if cl.exe is already in the path

        try:

            subprocess.check_output(["where", "/Q", "cl"])

        # If not, try to find an installation of Visual Studio and append the compiler dir to the path

        except subprocess.CalledProcessError as e:

            cl_path = find_msvc()
            if cl_path:
                if verbose:
                    print(" -- Injected compiler path:", cl_path)
                os.environ["path"] += ";" + cl_path
            else:
                print(" !! Unable to find cl.exe; compilation will probably fail", file = sys.stderr)


    # gcc / cl.exe flags

    extra_cflags = ["/Ox"] if windows else ["-O3"]

    if ext_debug:
        extra_cflags += ["-ftime-report", "-DTORCH_USE_CUDA_DSA"]


    # nvcc flags

    extra_cuda_cflags = ["-lineinfo", "-O3"]
    # extra_cuda_cflags += ["-maxrregcount=128"]


    # linker flags

    extra_ldflags = []

    if windows:
        extra_ldflags += ["cublas.lib"]
        if sys.base_prefix != sys.prefix:
            extra_ldflags += [f"/LIBPATH:{os.path.join(sys.base_prefix, 'libs')}"]


    # sources

    library_dir = os.path.dirname(os.path.abspath(__file__))
    sources_dir = os.path.join(library_dir, extension_name)

    sources_ = \
    [
        "ext.cpp",
        "cuda/pack_tensor.cu",
        "cuda/quantize.cu",
        "cuda/q_matrix.cu",
        "cuda/q_attn.cu",
        "cuda/q_mlp.cu",
        "cuda/q_gemm.cu",
        "cuda/rms_norm.cu",
        "cuda/rope.cu",
        "cpp/quantize_func.cpp",
        "cpp/sampling.cpp"
    ]

    sources = [os.path.join(sources_dir, s) for s in sources_]


    # Load extension

    exllamav2_ext = load \
    (
        name = extension_name,
        sources = sources,
        extra_include_paths = [sources_dir],
        verbose = verbose,
        extra_ldflags = extra_ldflags,
        extra_cuda_cflags = extra_cuda_cflags,
        extra_cflags = extra_cflags
    )

ext_c = exllamav2_ext
```

**Comment by DFuller134** [comment]
Not sure if this is a valid approach, but I modified `ext.py` to force execution of code starting at `# gcc / cl.exe flags` comment and got the following exception:

```
Traceback (most recent call last):
  File "/home/streamedge/projects/LLM/exllamav2-test/venv/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

**Comment by turboderp** [comment]
I think I get it now. The `import exllamav2_ext` line is supposed to be executed when importing the `exllamav2` library, and it's only supposed to succeed when the exllamav2_ext package is installed in your env. Otherwise, it raises an exception and loads the JIT version instead.

In your case, since you're specifying `PYTHONPATH=exllamav2`, it tries to load the extension from the `./exllamav2/` folder, where it finds a directory with the same name and no Python code, so it loads it as an empty package.

You shouldn't need to set the path like that, or if you do, I believe the correct path to provide would be one level higher, i.e. `.` in this case.

**Comment by DFuller134** [comment]
Great! Thanks! So then that now leaves us with the compilation error. Do you have an idea why Python.h is not available?

```
/home/streamedge/projects/LLM/exllamav2-test/venv/lib/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
   12 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
```

**Comment by DFuller134** [comment]
Thanks! Worked once I corrected the PYTHONPATH and another issue with header files.

**Comment by codenoid** [comment]
```
python3 examples/chat.py -m /home/rb/microsoft/phi-2 -mode llama

 -- Model: /home/rb/microsoft/phi-2
 -- Options: []
 !! Warning, unknown architecture: ['PhiForCausalLM']
 !! Loading as LlamaForCausalLM
Traceback (most recent call last):
  File "/home/rb/exllamav2/examples/chat.py", line 85, in <module>
    model, tokenizer = model_init.init(args, allow_auto_split = True)
  File "/home/rb/exllamav2/exllamav2/model_init.py", line 70, in init
    config.prepare()
  File "/home/rb/exllamav2/exllamav2/config.py", line 156, in prepare
    self.rms_norm_eps = read_config["rms_norm_eps"]
KeyError: 'rms_norm_eps'
```

is it the same error? as I try to set PYTHONPATH but no lock

**Comment by turboderp** [comment]
No, that's a different error. The reason is that phi-2 isn't supported.
